import { AnimatePresence, motion } from "framer-motion";
import { useRef, useState } from "react";
import type { KeyboardEvent } from "react";

const lenses = [
  { id: "voice", tab: "AI calling", org: "Your Glow", title: "Calls answered, services explained, appointments booked.", description: "A live voice workflow with booking, follow-up texts, and human escalation.", facts: ["Real callers", "Booking", "Follow-up SMS"], tabActive: "border-[var(--theme-sky)] bg-[var(--theme-sky)] text-[#071018]", panel: "from-[#0d3945] via-[#102d3a] to-[#10131c]", accent: "text-[var(--theme-sky)]", dot: "bg-[var(--theme-sky)]", iconBg: "bg-[var(--theme-sky)] text-[#071018]" },
  { id: "marketing", tab: "Marketing", org: "ForYouHub", title: "Campaigns, storefront growth, analytics, and support.", description: "Marketing operations connecting Shopify, TikTok creative, audience research, customer communication, and order support.", facts: ["Campaigns", "Shopify", "Audience growth"], tabActive: "border-[var(--theme-secondary)] bg-[var(--theme-secondary)] text-[#241804]", panel: "from-[#4a3511] via-[#302611] to-[#15120d]", accent: "text-[color-mix(in_srgb,var(--theme-secondary)_65%,white)]", dot: "bg-[var(--theme-secondary)]", iconBg: "bg-[var(--theme-secondary)] text-[#241804]" },
  { id: "web", tab: "Web", org: "Marlin Hotel", title: "Room browsing, booking, maps, and contact.", description: "A hotel website with room and amenity pages, inquiry paths, and an interactive walkthrough.", facts: ["Website", "Booking flow", "Walkthrough"], tabActive: "border-[var(--theme-primary)] bg-[var(--theme-primary)] text-[#2a0f0b]", panel: "from-[#4d211b] via-[#32201e] to-[#171114]", accent: "text-[color-mix(in_srgb,var(--theme-primary)_65%,white)]", dot: "bg-[var(--theme-primary)]", iconBg: "bg-[var(--theme-primary)] text-[#2a0f0b]" },
  { id: "community", tab: "Community", org: "Umeed + STELLAR Pakistan", title: "Scholarships, accessible art, and STEM outreach.", description: "Education access, mentoring, and adapted creative instruction for students and children.", facts: ["Scholarships", "Accessible art", "STEM outreach"], tabActive: "border-[var(--theme-tertiary)] bg-[var(--theme-tertiary)] text-[#092119]", panel: "from-[#12392c] via-[#183028] to-[#111815]", accent: "text-[color-mix(in_srgb,var(--theme-tertiary)_65%,white)]", dot: "bg-[var(--theme-tertiary)]", iconBg: "bg-[var(--theme-tertiary)] text-[#092119]" },
] as const;

function LensIcon({ id }: { id: (typeof lenses)[number]["id"] }) {
  if (id === "voice") return <svg viewBox="0 0 48 48" className="h-7 w-7" fill="none" aria-hidden="true"><path d="M12 15a12 12 0 0 1 24 0v13a8 8 0 0 1-8 8h-4" stroke="currentColor" strokeWidth="2.5" strokeLinecap="round"/><rect x="7" y="18" width="7" height="14" rx="3.5" stroke="currentColor" strokeWidth="2.5"/><rect x="34" y="18" width="7" height="14" rx="3.5" stroke="currentColor" strokeWidth="2.5"/><path d="M19 24c1.5-3 3 3 5 0s3.5 3 5-1" stroke="currentColor" strokeWidth="2.2" strokeLinecap="round"/><circle cx="24" cy="36" r="2.5" fill="currentColor"/></svg>;
  if (id === "marketing") return <svg viewBox="0 0 48 48" className="h-7 w-7" fill="none" aria-hidden="true"><path d="M8 31V17l23-8v30L8 31Z" stroke="currentColor" strokeWidth="2.5" strokeLinejoin="round"/><path d="M31 18h4a6 6 0 0 1 0 12h-4M13 32l3 8h8l-4-10" stroke="currentColor" strokeWidth="2.5" strokeLinecap="round" strokeLinejoin="round"/><path d="M35 12l5-4M37 19h6M35 36l5 4" stroke="currentColor" strokeWidth="2.2" strokeLinecap="round"/></svg>;
  if (id === "web") return <svg viewBox="0 0 48 48" className="h-7 w-7" fill="none" aria-hidden="true"><rect x="6" y="9" width="36" height="30" rx="5" stroke="currentColor" strokeWidth="2.5"/><path d="M6 18h36M13 13.5h.1M19 13.5h.1" stroke="currentColor" strokeWidth="2.5" strokeLinecap="round"/><path d="M14 31l6-6 5 4 8-8" stroke="currentColor" strokeWidth="2.5" strokeLinecap="round" strokeLinejoin="round"/><path d="M29 21h4v4" stroke="currentColor" strokeWidth="2.5" strokeLinecap="round" strokeLinejoin="round"/></svg>;
  return <svg viewBox="0 0 48 48" className="h-7 w-7" fill="none" aria-hidden="true"><circle cx="17" cy="18" r="6" stroke="currentColor" strokeWidth="2.4"/><circle cx="32" cy="19" r="5" stroke="currentColor" strokeWidth="2.4"/><path d="M7 38c1.5-7 5-11 10-11s9 4 10 11M25 38c1-5.5 3.5-9 7-9 4 0 7 3.5 8 9" stroke="currentColor" strokeWidth="2.4" strokeLinecap="round"/><path d="m22 10 2-4 2 4 4 .5-3 3 .8 4-3.8-2-3.8 2 .8-4-3-3 4-.5Z" fill="currentColor"/></svg>;
}

export default function HeroVisual() {
  const [active, setActive] = useState(0);
  const tabRefs = useRef<Array<HTMLButtonElement | null>>([]);
  const lens = lenses[active];
  const select = (index: number, focus = false) => { const normalized = (index + lenses.length) % lenses.length; setActive(normalized); if (focus) tabRefs.current[normalized]?.focus(); };
  const onTabKeyDown = (event: KeyboardEvent<HTMLButtonElement>, index: number) => {
    if (event.key === "ArrowRight" || event.key === "ArrowDown") { event.preventDefault(); select(index + 1, true); }
    if (event.key === "ArrowLeft" || event.key === "ArrowUp") { event.preventDefault(); select(index - 1, true); }
    if (event.key === "Home") { event.preventDefault(); select(0, true); }
    if (event.key === "End") { event.preventDefault(); select(lenses.length - 1, true); }
  };

  return <motion.div initial={{ opacity: 0, y: 22 }} animate={{ opacity: 1, y: 0 }} transition={{ duration: 0.7, delay: 0.16, ease: [0.22, 1, 0.36, 1] }} className="relative mx-auto w-full max-w-[37rem]">
    <div className="absolute -inset-8 rounded-[2.4rem] bg-[radial-gradient(circle_at_20%_20%,color-mix(in_srgb,var(--theme-sky)_16%,transparent),transparent_38%),radial-gradient(circle_at_85%_75%,color-mix(in_srgb,var(--theme-primary)_14%,transparent),transparent_40%)] blur-3xl" />
    <div className="relative overflow-hidden rounded-[1.7rem] border border-white/12 bg-[#0b0a10]/88 p-2.5 shadow-[0_30px_95px_-42px_rgba(0,0,0,.95)] backdrop-blur-2xl">
      <div className="flex items-center justify-between gap-4 px-2 pb-2 pt-1"><p className="text-[9px] font-semibold uppercase tracking-[0.23em] text-white/62">Selected work · choose a lane</p><div className="flex gap-1.5" aria-hidden="true"><span className="h-1.5 w-1.5 rounded-full bg-[var(--theme-primary)]"/><span className="h-1.5 w-1.5 rounded-full bg-[var(--theme-secondary)]"/><span className="h-1.5 w-1.5 rounded-full bg-[var(--theme-tertiary)]"/></div></div>
      <div className="grid grid-cols-2 gap-1.5 sm:grid-cols-4" role="tablist" aria-label="Portfolio work areas">
        {lenses.map((item, index) => <button key={item.id} ref={(node) => { tabRefs.current[index] = node; }} id={`portfolio-tab-${item.id}`} type="button" role="tab" tabIndex={active === index ? 0 : -1} aria-selected={active === index} aria-controls={`portfolio-panel-${item.id}`} onClick={() => select(index)} onKeyDown={(event) => onTabKeyDown(event, index)} className={`group min-h-12 rounded-xl border px-2 py-2 text-[9px] font-semibold transition duration-300 ${active === index ? item.tabActive : "border-white/8 bg-white/[0.03] text-white/62 hover:-translate-y-0.5 hover:border-white/18 hover:bg-white/[0.065] hover:text-white"}`}><span className="flex items-center justify-center gap-2"><span className={`grid h-6 w-6 place-items-center rounded-lg ${active === index ? "bg-black/10" : "bg-white/[0.04]"}`}><LensIcon id={item.id}/></span>{item.tab}</span></button>)}
      </div>
      <AnimatePresence mode="wait"><motion.div key={lens.id} id={`portfolio-panel-${lens.id}`} role="tabpanel" aria-labelledby={`portfolio-tab-${lens.id}`} initial={{ opacity: 0, y: 12, scale: .985 }} animate={{ opacity: 1, y: 0, scale: 1 }} exit={{ opacity: 0, y: -8, scale: .99 }} transition={{ duration: 0.28, ease: [0.22, 1, 0.36, 1] }} className={`relative mt-2.5 overflow-hidden rounded-2xl border border-white/10 bg-gradient-to-br ${lens.panel} p-4 sm:p-5`}>
        <div className="pointer-events-none absolute -right-16 -top-16 h-44 w-44 rounded-full bg-white/8 blur-3xl"/><div className="pointer-events-none absolute inset-0 opacity-[0.025] [background-image:radial-gradient(circle_at_center,rgba(255,255,255,.75)_1px,transparent_1px)] [background-size:22px_22px]"/>
        <div className="relative flex items-start justify-between gap-4"><div className="min-w-0"><div className="flex items-center gap-2"><span className={`h-1.5 w-1.5 rounded-full ${lens.dot}`}/><p className={`truncate text-[9px] font-semibold uppercase tracking-[0.18em] ${lens.accent}`}>{lens.org}</p></div><p className="mt-3 max-w-md text-[1.35rem] font-semibold leading-[1.08] text-white">{lens.title}</p></div><motion.div key={`${lens.id}-icon`} initial={{ rotate: -10, scale: .88 }} animate={{ rotate: 0, scale: 1 }} whileHover={{ rotate: 6, scale: 1.07 }} transition={{ type: "spring", stiffness: 240, damping: 18 }} className={`hidden h-14 w-14 shrink-0 place-items-center rounded-2xl border border-white/25 shadow-[0_18px_42px_-24px_rgba(255,255,255,.6)] sm:grid ${lens.iconBg}`}><LensIcon id={lens.id}/></motion.div></div>
        <p className="relative mt-3 max-w-xl text-[13px] leading-5 text-white/62">{lens.description}</p><div className="relative mt-4 flex flex-wrap gap-2">{lens.facts.map((fact, index) => <motion.span key={fact} initial={{ opacity: 0, y: 6 }} animate={{ opacity: 1, y: 0 }} transition={{ delay: index * .04 }} className="rounded-full border border-white/10 bg-black/15 px-3 py-1.5 text-[9px] font-medium text-white/62">{fact}</motion.span>)}</div>
      </motion.div></AnimatePresence>
    </div>
  </motion.div>;
}
